### ISSUE TITLE
Feature Request: Disable Mouse

### ISSUE THREAD

**Issue by gandl** [simonthechipmunk/turnoffdisplay#4]
Hi,

i really like your extension. It's very nice.
Would it be possible to add an Option that disables mouse input while the screen is off?
That way the keyboard had to be used to turn on the screen again and some over sensitve optical mouses wouldn't wake it up by accident.

greetings :)

**Comment by simonthechipmunk** [comment]
Hi,

I ran into this problem myself and will try to implement your idea as soon as possible. Right now I'm moving to another city, so this may take some time.

The most likely starting point for this would be the Touchpad-Indicator Extension, because I have no idea how to disable input devices.
https://github.com/orangeshirt/gnome-shell-extension-touchpad-indicator

Simon

**Comment by gandl** [comment]
Hi,

what about the tool xinput? It should be able to deactivate the mouse, but i don't know how one would enable it again after the monitor turned on.

Happy moving by the way. :)
