### ISSUE TITLE
Q: what is example value of keybinding?

### ISSUE THREAD

**Issue by biji** [simonthechipmunk/turnoffdisplay#9]
what is example value of keybinding?
I have tried to set Fn F11 , Ctrl Alt X , but not working

thanks

**Comment by simonthechipmunk** [comment]
Hi,

if you hover over the text in the settings dialog a tooltip with more
detailed instructions will pop up. It's a little hidden ;)
Sticking to your example for Ctrl Alt X you would need to enter 

<Ctrl><Alt>x

into the keybinding field (Any multiplier key is indicated by brackets
<>). The 'x' will then turn into a checkmark indicating that the
entered keybinding is correct and recognised.
I just discovered a bug with this so you may also ##SELECTION_END##have
to restart gnome-shell to make it work after entering a keybinding for
the first time.

I am however not sure how to do it using the Fn key, because it is (as
far as i know) not part of the standard keyset and therefore may vary
between manufacturers.
You may have to find out the corresponding keycode and set up a new
assignment before you can use the Fn key with the extension:

http://askubuntu.com/questions/80777/how-to-find-keycodes-for-fn-keys

https://help.ubuntu.com/community/MultimediaKeysx

**Comment by biji** [comment]
haha.. yes there's an instruction in tooltip 
ok, I will try your suggestion

thanks
